### ISSUE TITLE
SPI on ports 17,18,22 requires setting mode

### ISSUE THREAD

**Issue by kleykenb** [adafruit/Adafruit_Nokia_LCD#12]
To make this work on on BBB it was necessary to first set the pins in the correct mode : `# config-pin P9_17 spi_cs; config-pin P9_18 spi; config-pin P9_22 spi_sclk`

**Comment by kleykenb** [comment]
It's not an issue of the library itself, of course, but caused by changes in the way pinmux-ing on the OS needs to be done. 
An alternative to setting the pins manually is to edit /boot/uEnv.txt and replace
#uboot_overlay_addr4=/lib/firmware/<file4>.dtbo 
by
uboot_overlay_addr4=/lib/firmware/BB-SPIDEV0-00A0.dtbo
which will set the pins automatiically at boot.

**Comment by makermelissa** [comment]
Hi, this library is being deprecated. We're now using https://github.com/adafruit/Adafruit_CircuitPython_PCD8544. You can find more info in our learn guide:
https://learn.adafruit.com/nokia-5110-3310-monochrome-lcd/python-wiring
