### ISSUE TITLE
error: no such file or directory

### ISSUE THREAD

**Issue by godot11** [adafruit/Adafruit_Nokia_LCD#4]
I am new to Raspberry Pi and Python, and this is my second project. I did everything exactly as it is written in Adafruit's tutorial (https://learn.adafruit.com/nokia-5110-3310-lcd-python-library), but the code only returns a runtime error:

pi@raspberrypi ~/Adafruit_Nokia_LCD/examples $ sudo python image.py
Traceback (most recent call last):
  File "image.py", line 58, in <module>
    disp = LCD.PCD8544(DC, RST, spi=SPI.SpiDev(SPI_PORT, SPI_DEVICE, max_speed_hz=4000000))
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_GPIO-0.7.1-py2.7.egg/Adafruit_GPIO/SPI.py", line 42, in __init__
    self._device.open(port, device)
IOError: [Errno 2] No such file or directory

I don't really know what to do or even where to ask for help. I would be grateful if you could help me what to do.

**Comment by tdicola** [comment]
Oh make sure you've enabled SPI on the Raspberry Pi, from the error it looks like it can't find the path to the SPI device which typically means SPI is disabled.  There was actually a recent change to the raspi-config tool that lets you enable SPI through a simple menu, check out the instructions here: http://www.raspberrypi-spy.co.uk/2014/08/enabling-the-spi-interface-on-the-raspberry-pi/

For reference too, if you ever want to manually enable SPI (and I2C), check out the guide here: https://learn.adafruit.com/adafruits-raspberry-pi-lesson-4-gpio-setup/configuring-i2c  The important bit is commenting out the blacklist of the spi-bcm2708 module.

And one last brand new option is trying the Pi Bootstrapper: https://github.com/adafruit/Adafruit-Pi-Finder#adafruit-raspberry-pi-finder  This will find your Pi and automatically enable I2C, SPI, and install a few other commonly used things.  You might check that too if you have trouble with enabling SPI through other means.
