### ISSUE TITLE
LCD goes blank and file descriptor leak?

### ISSUE THREAD

**Issue by RigacciOrg** [adafruit/Adafruit_Nokia_LCD#5]
Hi,

I'm using this library on the Raspberry Pi. The main program is a Python daemon to control a programmable thermostat.

Sometimes the LCD goes blank without any apparent reason. The program is fully functional, the Python image saved as PNG is OK, but disp.image() and disp.display() seems to do nothing anymore.

Every 3 minutes - as a workaround - I re-initialize the LCD, using:

   disp = LCD.PCD8544(...)
   disp.begin(contrast=LCD_CONTRAST)
   disp.clear()

This is effective in making the display working again, but I suffer from a file descriptor leakage: I can see  an increasing number of N -> /dev/spidev0.0 into /proc/PID/fd/ and after about three days the program dies.

Is there a nice way to release the resources? Any hints on the blank LCD problem?

Thank you

**Comment by RigacciOrg** [comment]
The file descriptor leakage seems to be solved. Unfortunately I don't know what was the programming error I made.

The LCD still goes blank sometimes. I suspect a problem caused by updating the LCD in two different program threads. May be the library is not thread-safe?

**Comment by RigacciOrg** [comment]
Hi to all.
I am almost sure that the problem with the LCD going blank, was originated by **the library not being thread-safe**.

I have several program threads updating different parts of the LCD, I solved the problem putting `lcd_disp.image()` and `lcd_disp.display()` function calls into a semaphore block.

Something like this:

```python
import threading

lcd_sema = threading.BoundedSemaphore()

sub display_something():
    global lcd_disp, lcd_draw, lcd_image, lcd_sema
    lcd_draw.rectangle((0, 32, 43, 38), outline=255, fill=255)
    with lcd_sema:
        lcd_disp.image(lcd_image)
        lcd_disp.display()

**Comment by ladyada** [comment]
nice find! can you submit a pull req for the thread support?
