### ISSUE TITLE
Adafruit Tutorial missing a step for Raspberry Pi

### ISSUE THREAD

**Issue by ShadGates** [adafruit/Adafruit_Nokia_LCD#6]
The tutorial at https://learn.adafruit.com/nokia-5110-3310-lcd-python-library/usage
fails with a file not found error on the step running the line **"sudo python setup.py install"**.

This is on a clean Raspbian image (the new version, supporting Pi 2). 

I was able to figure out that it was missing the python-dev package, and get it working by executing **"sudo apt-get install python-dev"**, then re-running that final line **"sudo python setup.py install"**.

It would be great for newer users attempting to run the tutorials if you could add the step to install the python-dev package before the execution of **"sudo python setup.py install"**.

**Comment by tdicola** [comment]
Oh thanks for raising the issue and suggesting the fix.  I just updated the guide to list python-dev in the instructions.  Thanks again for helping improve the library and guide!
